import type { Inquiry } from '@/types/content';
import { L } from './helpers';
import type { Settings } from '@/types/content';

/** Twelve inquiries across every source type, status, and locale. */
export const mockInquiries: Inquiry[] = [
  {
    id: 'inq_01',
    name: 'Anindita Rahmawati',
    email: 'anindita@northbaycoffee.id',
    company: 'Northbay Coffee',
    phone: '+62 812 3344 5566',
    subject: 'Packaging system for 9 SKUs',
    message:
      'We are relaunching our retail line in Q1 and currently have nine bag designs that do not relate to each other. Saw the Nocturne case study - that is roughly the problem we have. Budget is not fixed yet but we are serious about doing it properly.',
    budgetRange: '50-200m',
    sourceType: 'service',
    sourceId: 'svc_packaging',
    sourceTier: 'gold',
    locale: 'en',
    status: 'new',
    createdAt: '2026-08-02T04:12:00.000Z',
    readAt: null,
    repliedAt: null,
    meta: { ip: '103.28.14.201', userAgent: 'Mozilla/5.0 (Macintosh)', referrer: '/en/services/packaging-design' },
  },
  {
    id: 'inq_02',
    name: 'Bagus Prasetyo',
    email: 'bagus@tanamkan.co.id',
    company: 'Tanamkan',
    phone: null,
    subject: 'Aplikasi lapangan untuk tim agronomi',
    message:
      'Tim kami bekerja di kebun dengan sinyal minim, sekarang masih pakai kertas lalu diinput ulang malam hari. Studi kasus Tessera sangat mirip dengan kebutuhan kami. Boleh dijadwalkan diskusi minggu depan?',
    budgetRange: '200m+',
    sourceType: 'project',
    sourceId: 'proj_tessera',
    sourceTier: null,
    locale: 'id',
    status: 'read',
    createdAt: '2026-07-30T08:45:00.000Z',
    readAt: '2026-07-30T10:02:00.000Z',
    repliedAt: null,
    meta: { ip: '182.253.44.9', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', referrer: '/id/work/tessera-field-app' },
  },
  {
    id: 'inq_03',
    name: 'Clara Wijaya',
    email: 'clara.w@meridianfreight.com',
    company: 'Meridian Freight',
    phone: '+62 811 9922 3344',
    subject: 'Phase two - driver payments module',
    message:
      'Following up on the platform you built for us last year. We want to add a driver settlement and payments module. Same team if possible.',
    budgetRange: '200m+',
    sourceType: 'contact',
    sourceId: null,
    sourceTier: null,
    locale: 'en',
    status: 'replied',
    createdAt: '2026-07-24T02:30:00.000Z',
    readAt: '2026-07-24T03:15:00.000Z',
    repliedAt: '2026-07-24T06:40:00.000Z',
    meta: { ip: '103.10.66.77', userAgent: 'Mozilla/5.0 (Macintosh)', referrer: '/en/contact' },
  },
  {
    id: 'inq_04',
    name: 'Dimas Nugroho',
    email: 'dimas@kelanastudio.id',
    company: 'Kelana Studio',
    phone: null,
    subject: 'Lisensi Forge untuk tim 12 orang',
    message:
      'Kami tertarik dengan Forge untuk menyatukan design token antara Figma dan repo. Tim desain 4 orang, engineer 8 orang. Apakah ada opsi self-hosted?',
    budgetRange: '<10m',
    sourceType: 'product',
    sourceId: 'prod_forge',
    sourceTier: null,
    locale: 'id',
    status: 'replied',
    createdAt: '2026-07-19T07:20:00.000Z',
    readAt: '2026-07-19T07:55:00.000Z',
    repliedAt: '2026-07-19T09:10:00.000Z',
    meta: { ip: '114.79.20.5', userAgent: 'Mozilla/5.0 (X11; Linux x86_64)', referrer: '/id/products/forge' },
  },
  {
    id: 'inq_05',
    name: 'Erika Santoso',
    email: 'erika@vantageaudio.com',
    company: 'Vantage Audio',
    phone: '+62 813 5566 7788',
    subject: 'Second product film - over-ear line',
    message:
      'The first film performed far beyond what we expected. We have a second product coming in November and would like to run the same process. CAD will be ready end of August.',
    budgetRange: '50-200m',
    sourceType: 'service',
    sourceId: 'svc_animation',
    sourceTier: 'gold',
    locale: 'en',
    status: 'read',
    createdAt: '2026-07-15T11:05:00.000Z',
    readAt: '2026-07-15T12:30:00.000Z',
    repliedAt: null,
    meta: { ip: '202.80.12.3', userAgent: 'Mozilla/5.0 (Macintosh)', referrer: '/en/services/3d-animation' },
  },
  {
    id: 'inq_06',
    name: 'Farid Hidayat',
    email: 'farid@hidayatlegal.id',
    company: 'Hidayat & Partners',
    phone: '+62 815 1122 3344',
    subject: 'Quarry beta access',
    message:
      'We hold roughly 40,000 scanned case documents that cannot leave our office. Read that Quarry runs locally - we would like to join the beta.',
    budgetRange: 'undecided',
    sourceType: 'product',
    sourceId: 'prod_quarry',
    sourceTier: null,
    locale: 'en',
    status: 'new',
    createdAt: '2026-07-12T03:48:00.000Z',
    readAt: null,
    repliedAt: null,
    meta: { ip: '36.72.88.14', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', referrer: '/en/products/quarry' },
  },
  {
    id: 'inq_07',
    name: 'Gita Larasati',
    email: 'gita@arunika.co',
    company: 'Arunika',
    phone: null,
    subject: 'Identitas merek untuk perusahaan baru',
    message:
      'Kami perusahaan energi terbarukan yang baru berdiri, butuh identitas lengkap termasuk panduan penerapan. Target peluncuran Februari 2027.',
    budgetRange: '50-200m',
    sourceType: 'pricing',
    sourceId: 'svc_brand',
    sourceTier: 'gold',
    locale: 'id',
    status: 'replied',
    createdAt: '2026-07-08T06:15:00.000Z',
    readAt: '2026-07-08T07:00:00.000Z',
    repliedAt: '2026-07-09T02:20:00.000Z',
    meta: { ip: '110.138.9.44', userAgent: 'Mozilla/5.0 (iPhone)', referrer: '/id/pricing' },
  },
  {
    id: 'inq_08',
    name: 'Hendra Kusuma',
    email: 'hendra@pasarlokal.id',
    company: 'Pasar Lokal',
    phone: '+62 819 4455 6677',
    subject: 'Audit arsitektur - platform lambat',
    message:
      'Platform kami makin lambat setiap bulan dan tim internal tidak sepakat penyebabnya. Butuh pandangan dari luar sebelum memutuskan rebuild atau perbaiki.',
    budgetRange: '10-50m',
    sourceType: 'service',
    sourceId: 'svc_consulting',
    sourceTier: null,
    locale: 'id',
    status: 'read',
    createdAt: '2026-07-03T09:35:00.000Z',
    readAt: '2026-07-03T10:10:00.000Z',
    repliedAt: null,
    meta: { ip: '125.166.4.88', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', referrer: '/id/services/technical-consulting' },
  },
  {
    id: 'inq_09',
    name: 'Intan Permata',
    email: 'intan@kilnstudio.id',
    company: 'Kiln Studio',
    phone: null,
    subject: 'Commission pipeline improvements',
    message:
      'The waitlist feature is doing more volume than we planned for. We would like to turn it into a proper commission workflow with deposits and stage updates.',
    budgetRange: '10-50m',
    sourceType: 'project',
    sourceId: 'proj_kiln',
    sourceTier: null,
    locale: 'en',
    status: 'archived',
    createdAt: '2026-06-21T05:00:00.000Z',
    readAt: '2026-06-21T05:40:00.000Z',
    repliedAt: '2026-06-22T01:15:00.000Z',
    meta: { ip: '103.47.132.6', userAgent: 'Mozilla/5.0 (Macintosh)', referrer: '/en/work/kiln-ceramics-commerce' },
  },
  {
    id: 'inq_10',
    name: 'Joko Susilo',
    email: 'joko@terangdata.id',
    company: 'Terang Data',
    phone: '+62 817 7788 9900',
    subject: 'Strata untuk 6 repository',
    message:
      'Tagihan cloud kami naik terus tanpa ada yang bisa menjelaskan. Tertarik memakai Strata di enam repository infrastruktur kami.',
    budgetRange: '<10m',
    sourceType: 'pricing',
    sourceId: 'prod_strata',
    sourceTier: null,
    locale: 'id',
    status: 'new',
    createdAt: '2026-06-14T04:25:00.000Z',
    readAt: null,
    repliedAt: null,
    meta: { ip: '116.206.11.90', userAgent: 'Mozilla/5.0 (X11; Linux x86_64)', referrer: '/id/pricing' },
  },
  {
    id: 'inq_11',
    name: 'Karina Dewi',
    email: 'karina@haldenarch.com',
    company: 'Halden Architecture',
    phone: null,
    subject: 'Signage extension for two new offices',
    message:
      'We are opening in Surabaya and Bali. Need the signage system extended and a short workshop for both new teams.',
    budgetRange: '10-50m',
    sourceType: 'project',
    sourceId: 'proj_halden',
    sourceTier: null,
    locale: 'en',
    status: 'archived',
    createdAt: '2026-05-30T08:10:00.000Z',
    readAt: '2026-05-30T08:45:00.000Z',
    repliedAt: '2026-05-31T03:30:00.000Z',
    meta: { ip: '203.142.77.21', userAgent: 'Mozilla/5.0 (Macintosh)', referrer: '/en/work/halden-identity-system' },
  },
  {
    id: 'inq_12',
    name: 'Lukman Hakim',
    email: 'lukman@sinargroup.co.id',
    company: 'Sinar Group',
    phone: '+62 812 0099 8877',
    subject: 'Website perusahaan + portal karier',
    message:
      'Butuh website korporat baru sekaligus portal karier terintegrasi. Saat ini masih WordPress lama dan sulit diperbarui.',
    budgetRange: '50-200m',
    sourceType: 'service',
    sourceId: 'svc_web',
    sourceTier: 'basic',
    locale: 'id',
    status: 'replied',
    createdAt: '2026-05-18T02:55:00.000Z',
    readAt: '2026-05-18T03:20:00.000Z',
    repliedAt: '2026-05-18T07:45:00.000Z',
    meta: { ip: '180.245.30.7', userAgent: 'Mozilla/5.0 (Windows NT 10.0)', referrer: '/id/services/web-app-development' },
  },
];

export const mockSettings: Settings = {
  studioName: 'QORV Studio',
  tagline: L('Digital & physical architecture.', 'Arsitektur digital & fisik.'),
  foundedYear: 2018,
  location: L('Indonesia', 'Indonesia'),
  email: 'studio@qorv.id',
  whatsapp: '6281234567890',
  address: L('Jakarta, Indonesia', 'Jakarta, Indonesia'),
  socials: [
    { platform: 'Instagram', url: 'https://instagram.com/qorvstudio' },
    { platform: 'Behance', url: 'https://behance.net/qorvstudio' },
    { platform: 'GitHub', url: 'https://github.com/qorvstudio' },
    { platform: 'LinkedIn', url: 'https://linkedin.com/company/qorvstudio' },
  ],
  seoDefaults: {
    title: L('QORV - Digital & Physical Architecture', 'QORV - Arsitektur Digital & Fisik'),
    description: L(
      'We engineer function, not decoration. Web and app development, 3D and animation, packaging and brand systems.',
      'Kami merekayasa fungsi, bukan sekadar dekorasi. Pengembangan web dan aplikasi, 3D dan animasi, kemasan dan sistem merek.',
    ),
    ogImage: null,
  },
  updatedAt: '2026-07-01T09:00:00.000Z',
};
